name: Unit Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true

      - name: Install dependencies
        shell: bash
        run: |
          set -euxo pipefail
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # ensure ts-node present for jest.config.ts
      - name: Ensure ts-node is available for Jest
        run: npm ls ts-node || npm i -D ts-node

      - name: Run unit tests
        run: npm run test:unit -- --ci
